Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
Style/StringLiterals:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/LineLength:
  Max: 100
  Exclude:
    - spec/*
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ops_team.gemspec
Style/IfUnlessModifier:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
