Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
Style/StringLiterals:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - spec/*
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ops_team.gemspec
Style/IfUnlessModifier:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/PerceivedComplexity:
  Max: 8
Metrics/ClassLength:
  Max: 120
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Style/FormatStringToken:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
